### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by XDracam** [DanVioletSagmiller/UnitySOLID#1]
I am not sure whether this is the right place to ask, but what is the state of this project? It seems really useful but still has a lot of potential (especially looking at the roadmap in the readme)

Would be nice to get an update

**Comment by XDracam** [comment]
Also, what's the license for code in this repository? I'd like to add some things to an MIT-licensed open source unity library (no self-promotion here unless asked for)

**Comment by DanVioletSagmiller** [comment]
Sorry for the late delay.  You are welcome to use the code however you wish.  I created it.  And except for a few cases, I feel like it is overkill.  I.e. if you need CI but not on a build server that supports unity, and want testing to run with  it, this can work.  If your project requires TPS forms filled out.  Or, if running your unit tests in MS Test or nunit as part of an existing suite is really important.

But feel free to use all of the code base however you wish.  CC0

**Comment by DanVioletSagmiller** [comment]
I have edited the readme to reflect CC0  :)

**Comment by DanVioletSagmiller** [comment]
Should have marked it completed with the last update.
